### ISSUE TITLE
Ip string field, array in yml

### ISSUE THREAD

**Issue by gonzalovilaseca** [lennerd/VipxBotDetectBundle#4]
Ip is defined as a string, but in extended_bot.yml for example, it's defined as an array:

```
    Yigg:
        agent: ''
        ip: [188.138.56.55, 188.138.48.253]
        type: bot
```

So when matching `return $this->ip === $ip;` even if the ip is in the array, it won't match.
